/* eslint-disable */
module.exports = {
  getUser: '/back/user',
  showsupervisor: '/back/supervisor/showsupervisor',
  // 登陆
  login: '/back/login',
  // 首页
  home: '/home',
  // 顾问列表
  listcounselors: '/employee/listcounselors',
  // 美容师列表
  listbeauticians: '/employee/listbeauticians',
  // 门店区域列表
  liststoreareas: '/employee/liststoreareas',
  // 根据区域id查询门店列表
  liststores: '/employee/liststores',
  // 获取员工最大编号（7、8重复）
  liststores: '/employee/liststores',
  // 添加顾问
  savecounselor: '/employee/savecounselor',
  // 添加美容师
  savebeautician: '/employee/savebeautician',
  // 根据门店id获取该门店顾问列表
  getcounselorsofstore: '/employee/getcounselorsofstore',
  // 编辑顾问信息
  updatecounselor: '/employee/updatecounselor',
  // 编辑美容师信息
  updatebeautician: '/employee/updatebeautician',
  // 获取顾问详情
  getcounselordetail: '/employee/getcounselordetail',
  // 获取顾问当月佣金明细
  listcounselorcurmonbonus: '/employee/listcounselorcurmonbonus',
  // 16、获取美容师详情
  getbeauticiandetail: '/employee/getbeauticiandetail',
  //  获取美容师当月佣金明细
  listbeauticiancurmonbonus: '/employee/listbeauticiancurmonbonus',
  // 获取用户列表
  listmember: '/user/listmember',
  // 获取会员|顾客详情(请求与响应有区别)
  getcustomerdetail: '/user/getcustomerdetail',
  // 获取用户当月佣金列表信息
  listusercurmonbonus: '/user/listusercurmonbonus',
  // 获取会员卡服务记录
  listcarduse: '/user/listcarduse',
  // 22、23 获取会员卡服务记录(文档中的请求响应不一样，待修正？)
  listcarduse: '/user/listcarduse',
  // 修改邀请人信息
  updateinviter: '/user/updateinviter',
  // 根据userId获取直接邀请人信息
  getinviterinfo: '/user/getinviterinfo',
  // 顾客列表
  listcustomer: '/user/listcustomer',
  // 获取平台概况
  getplatformoverview: '/overview/getplatformoverview',
  // 获取平台当日概况
  getdayplatformoverview: '/overview/getdayplatformoverview',
  // 获取平台管理费列表
  listplatformfee: '/fee/listplatformfee',
  // 后台佣金列表
  listbonus: '/bonus/listbonus',
}
